#!/bin/bash

#delete build
if [ -d "./build/" ]; then
    rm -r ./build/
fi

#delete project
if [ -d "./CMakeFiles/" ]; then
    rm -r ./CMakeFiles/
fi

if [ -f "./CMakeCache.txt" ]; then
    rm ./CMakeCache.txt
fi

if [ -f "./cmake_install.cmake" ]; then
    rm ./cmake_install.cmake
fi

if [ -f "./Makefile" ]; then
    rm ./Makefile
fi

#delete example_main
if [ -d "./example_main/CMakeFiles/" ]; then
    rm -r ./example_main/CMakeFiles/
fi

if [ -f "./example_main/cmake_install.cmake" ]; then
    rm ./example_main/cmake_install.cmake
fi

if [ -f "./example_main/Makefile" ]; then
    rm ./example_main/Makefile
fi

#delete plugin_demo
if [ -d "./plugin_demo/CMakeFiles/" ]; then
    rm -r ./plugin_demo/CMakeFiles/
fi

if [ -f "./plugin_demo/cmake_install.cmake" ]; then
    rm ./plugin_demo/cmake_install.cmake
fi

if [ -f "./plugin_demo/Makefile" ]; then
    rm ./plugin_demo/Makefile
fi

#delete plugin_test
if [ -d "./plugin_test/CMakeFiles/" ]; then
    rm -r ./plugin_test/CMakeFiles/
fi

if [ -f "./plugin_test/cmake_install.cmake" ]; then
    rm ./plugin_test/cmake_install.cmake
fi

if [ -f "./plugin_test/Makefile" ]; then
    rm ./plugin_test/Makefile
fi

echo "clear vas_lpf example finished !"