#!/bin/bash

#plugin.test

echo "start clearing plugin.test !"

cd plugin_test

./clear

echo "finish clearing plugin.test !"

#plugin.demo

echo "start clearing plugin.demo !"

cd ../plugin_demo

./clear

echo "finish clearing plugin.demo !"

#example main

echo "start clearing example main !"

cd ../

rm -r build/ CMakeCache.txt CMakeFiles/ cmake_install.cmake Makefile

echo "finish clearing example main !"
