#!/bin/bash

#plugin.test

echo "start generating plugin.test !"

cd plugin_test

./generate

echo "finish generating plugin.test !"

#plugin.demo

echo "start generating plugin.demo !"

cd ../plugin_demo

./generate

echo "finish generating plugin.demo !"

#example main

echo "start generating example main !"

cd ../

cmake CMakeLists.txt

make

echo "finsih generating example main !"
