#!/bin/bash

# help
if [ "$1" = "-h" -o "$1" = "--help" -o $# = 0 ]; then
    echo "vas_lpf library help !"
    echo "generate parameter:"
    echo "    -h:        vas_lpf library help"
    echo "    -help:     vas_lpf library help"
    echo "    -shared:   library type = shared"
    echo "    -static:   library type = static"
    exit 0
# shared
elif [ "$1" = "-shared" ]; then
    echo "VAS_LIB_TYPE=SHARED"
    _VAS_LIB_TYPE=SHARED
# static
elif [ "$1" = "-static" ]; then
    echo "VAS_LIB_TYPE=STATIC"
    _VAS_LIB_TYPE=STATIC
else
    echo "Unknow parameter ! Please input parameter \"-h\" or \"--help\" for help !"
    exit 0
fi
# endif

if [ ! -d "./build/" ]; then
    mkdir ./build/
fi

if [ ! -d "./build/include/" ]; then
    mkdir ./build/include/
fi

if [ ! -d "./build/libs/" ]; then
    mkdir ./build/libs/
fi

cp *.h ./build/include

cmake -DCMAKE_BUILD_TYPE=Debug -DVAS_LIB_TYPE=$_VAS_LIB_TYPE CMakeLists.txt

make

cmake -DCMAKE_BUILD_TYPE=Release -DVAS_LIB_TYPE=$_VAS_LIB_TYPE CMakeLists.txt

make

echo "generate vas_lpf library finished !"